import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from "../../public/images/profile/image4.png"
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icon';


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout>
          <div className="flex items-center justify-between w-full">
            <div>
              <Image src={profilePic} alt="CodeBucks" className='w-full h-auto'></Image>
            </div>

            <div className='w-1/2 flex flex-col items-center self-center'>
              <AnimatedText text="Driving Excellence with Data, Design, and Determination" className='!text-6xl !text-left' />
              {/* <p> Motivated B.Tech student in Computer Science and Engineering with strong technical expertise in Python, C++, machine learning, and cybersecurity. Passionate about leveraging my skills and project experience, such as building facial recognition and disease prediction systems, to develop innovative solutions. Dedicated to continuous learning and contributing to impactful, technology-driven initiatives. </p> */}

              <p className='my-4 text-base font-medium'>Data Science enthusiast skilled in Python, SQL, and machine learning, with experience in data analysis, predictive modeling, and visualization. Passionate about solving problems and creating impactful, data-driven solutions.</p>
              <div className='felx items-center self-start mt-2'>

                <Link href="/Bijay Prasad Shah Rauniyar_Data Science.pdf" target={"_blank"}
                className="flex items-center bg-dark text-light p-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark 
                border-2 border-solid border-transparent hover:border-dark
                "
                // download={true}
                >Resume <LinkArrow className={"w-6 ml-1"}/>
                
                </Link>
                <Link href="mailto:bijayrauniyar90@gmail.com" target={"_blank"}
                className="ml-4 text-lg font-medium capitalize text-dark underline"
                >Contact</Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
