import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from "../../public/images/profile/image4.png"


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout>
          <div className="flex items-center justify-between w-full">
            <div>
              <Image src={profilePic} alt="CodeBucks" className='w-full h-auto'></Image>

            </div>

          </div>
        </Layout>
      </main>
    </>
  );
}
